### ISSUE TITLE
build: Meta-issue for follow-ups to initial CMake merge (#1113)

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1224]
Issues that have been (re)discovered in #1113 but have not been addressed there: 

Affecting both build systems:
 - [ ] Unified docs for configuration autotools/CMake/manual builds (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1171307979 and  https://github.com/bitcoin-core/secp256k1/pull/1142)
 - [ ] Improve MSVC warning options (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124276576)
 - [ ] Set `-fvisibility-inlines-hidden`? (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124273356)
 - [ ] Consider changing `DLL_EXPORT` TO `SECP256k1_DLL_EXPORT` (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1126797102)
 - [ ] Consider setting CMake's default of /MD for MSVC also in autotools builds. Perhaps make `CMAKE_MSVC_RUNTIME_LIBRARY` a CMake cache variable. (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1458005771)
 - [ ] Print out a warning in the tests if both `VERIFY` and `COVERAGE` are defined. For clarity, this should be done in the C source, not in the build system. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1127856040)
 - [ ] Consider dropping support for Valgrind on MacOS (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1128588031)
 - [ ] Actually check if ARM assembly is supported (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1460298292 and also tracked in https://github.com/bitcoin-core/secp256k1/issues/1034) 

Affecting only CMake:
 - [x] Changelog entry (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1460298292; solved by #1125)
 - [ ] Add CMake instructions to release process (solved by #1226)
 - [ ] Compute string `secp256k1` (e.g., in `target_link_libraries`) as substring of `PROJECT_NAME`. That will help with distinguishing forks. (https://github.com/bitcoin-core/secp256k1/pull/1229#discussion_r1130064718).
 - [ ] Consider recommending CMake-native build commands in the README (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124301931)
 - [ ] Consider using `COMPILE_FLAGS` or `COMPILE_OPTIONS` to add CFLAGS. `COMPILE_OPTIONS` requires CMake 3.11, while we currently target CMake 3.1 (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1125545613) 
 - [ ] Use `GENERATOR_IS_MULTI_CONFIG` in the future, which requires CMake 3.9. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124460512)
 - [ ] See if we can use CMake templates to have something similar to `--enable-dev-mode`. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r912386477)
 - [ ] Consider dropping support for building static and shared libraries at the same time (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1128702492)  or alternatively, enable position-independent code globally (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124264718)
 - [ ] `configure_package_config_file(... COMPATIBILITY` is `SameMajorVersion` but should probably be `SameMinorVersion` before 1.0.0 according to [our SemVer interpretation](https://github.com/bitcoin-core/secp256k1/pull/1223#issuecomment-1460481114). But the latter requires CMake 3.11. (https://gnusha.org/secp256k1/2023-03-08.log)
 - [ ] `make check` should run tests in parallel, like `ctest -j` (https://gnusha.org/secp256k1/2023-03-08.log)

**Comment by real-or-random** [comment]
I'm happy to fan out some of these items of these as full Github issues. But doing so for every item would probably flood the issue tracker. So I suggest we do this lazily, which helps also to keep the discussions separated:
 - If it's clear how to address an item, open a (draft) PR and we can discuss there.
 - If you want to discuss an item without opening a PR, just open an issue and start the discussion.

**Comment by theuni** [comment]
> - Consider dropping support for building static and shared libraries at the same time

I'll work on a POC of this for discussion.

**Comment by real-or-random** [comment]
Moving to #1235 to make sure @hebasto can edit the list.
