### ISSUE TITLE
build: Meta-issue for follow-ups to initial CMake merge (#1113)

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/secp256k1#1235]
Issues that have been (re)discovered in #1113 but have not been addressed there: 

Affecting both build systems:
 - [ ] Unified docs for configuration autotools/CMake/manual builds (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1171307979 and  https://github.com/bitcoin-core/secp256k1/pull/1142); WIP -- https://github.com/bitcoin-core/secp256k1/pull/1372
 - [x] Improve MSVC warning options (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124276576); solved by https://github.com/bitcoin-core/secp256k1/pull/1328
 - [x] Consider changing `DLL_EXPORT` TO `SECP256k1_DLL_EXPORT` (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1126797102); solved by https://github.com/bitcoin-core/secp256k1/pull/1367
 - ~Consider setting CMake's default of /MD for MSVC also in autotools builds. Perhaps make `CMAKE_MSVC_RUNTIME_LIBRARY` a CMake cache variable. (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1458005771)~ See https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1609373112 and https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1609503130
 - [x] Print out a warning in the tests if both `VERIFY` and `COVERAGE` are defined. For clarity, this should be done in the C source, not in the build system. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1127856040); solved by https://github.com/bitcoin-core/secp256k1/pull/1333
 - [x] Actually check if ARM assembly is supported (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1460298292 and also tracked in https://github.com/bitcoin-core/secp256k1/issues/1034); solved by https://github.com/bitcoin-core/secp256k1/pull/1304 
 - ~Set `-fvisibility-inlines-hidden`? (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124273356).~ See https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1466477275.
 -  ~Consider dropping support for Valgrind on MacOS (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1128588031).~ See https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1506878980.

Affecting only CMake:
 - [x] Changelog entry (https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1460298292; solved by #1225)
 - [x] Add CMake instructions to release process (solved by #1226)
 - [ ] Compute string `secp256k1` (e.g., in `target_link_libraries`) as substring of `PROJECT_NAME`. That will help with distinguishing forks. (https://github.com/bitcoin-core/secp256k1/pull/1229#discussion_r1130064718).
 - [x] Consider recommending CMake-native build commands in the README (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124301931, solved by #1483)
 - [x] Use `GENERATOR_IS_MULTI_CONFIG` in the future, which requires CMake 3.9. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124460512; solved by #1239)
 - [x] See if we can use CMake templates to have something similar to `--enable-dev-mode`. (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r912386477; solved by #1234)
 - [x] Consider dropping support for building static and shared libraries at the same time (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1128702492)  or alternatively, enable position-independent code globally (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124264718; solved by #1230)
 - [x] `configure_package_config_file(... COMPATIBILITY` is `SameMajorVersion` but should probably be `SameMinorVersion` before 1.0.0 according to [our SemVer interpretation](https://github.com/bitcoin-core/secp256k1/pull/1223#issuecomment-1460481114). But the latter requires CMake 3.11. (https://gnusha.org/secp256k1/2023-03-08.log; solved by #1239)
 - ~`make check` should run tests in parallel, like `ctest -j` (https://gnusha.org/secp256k1/2023-03-08.log; WIP in by https://github.com/bitcoin-core/secp256k1/pull/1294~
 - ~Consider using `COMPILE_FLAGS` or `COMPILE_OPTIONS` to add CFLAGS. `COMPILE_OPTIONS` requires CMake 3.11, while we currently target CMake 3.1 (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1125545613)~ See https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1479363026
 - ~Consider [CMAKE_COMPILE_WARNING_AS_ERROR](https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILE_WARNING_AS_ERROR.html) for CMake 3.24+ (https://github.com/bitcoin-core/secp256k1/pull/1241#issuecomment-1509008580)~ See https://github.com/bitcoin-core/secp256k1/issues/1235#issuecomment-1609567532
 - [x] Make `SECP256K1_INSTALL` default to `PROJECT_IS_TOP_LEVEL` on CMake 3.21+ (https://github.com/bitcoin-core/secp256k1/pull/1263); solved by #1284

**Comment by theuni** [comment]
Another one for me: my mingw32 build with ctests fails due to missing valgrind:
```bash
Valgrind .............................. OFF
...
ctime_tests ......................... ON
...
```

> /home/cory/dev/secp256k1/src/ctime_tests.c:14:4: error: #error "This tool cannot be compiled without memory-checking interface (valgrind or msan)"
>    14 | #  error "This tool cannot be compiled without memory-checking interface (valgrind or msan)"
> 

Should ctime_tests be a dependent option, depending on valgrind?

**Comment by hebasto** [comment]
@theuni 
> Another one for me: my mingw32 build with ctests fails due to missing valgrind:
> 
> ```shell
> Valgrind .............................. OFF
> ...
> ctime_tests ......................... ON
> ...
> ```
> 
> > /home/cory/dev/secp256k1/src/ctime_tests.c:14:4: error: #error "This tool cannot be compiled without memory-checking interface (valgrind or msan)"
> > 14 | #  error "This tool cannot be compiled without memory-checking interface (valgrind or msan)"

Do I understand correctly, that option `-DSECP256K1_BUILD_CTIME_TESTS=ON` is forced, right?

> Should ctime_tests be a dependent option, depending on valgrind?

I don't think so, as MSan is another option to use for building the `ctime_tests`.

**Comment by theuni** [comment]
> Do I understand correctly, that option -DSECP256K1_BUILD_CTIME_TESTS=ON is forced, right?

Yes, it was leftover on my cmdline from a previous build.

But on my win32 build with no valid runtime (valgrind/msan/whatever) I believe cmake should throw an error telling me  "SECP256K1_BUILD_CTIME_TESTS can't be set without valgrind/msan".

**Comment by hebasto** [comment]
> But on my win32 build with no valid runtime (valgrind/msan/whatever) I believe cmake should throw an error telling me "SECP256K1_BUILD_CTIME_TESTS can't be set without valgrind/msan".

Sounds like a nice feature for _both_ build systems--CMake based one and Autotools-based other.

**Comment by hebasto** [comment]
The current Autotools-based build system provides a user with an option to override compiler flags using the `CFLAGS` variable.

That is not the case in the new CMake-based build system for now. The order of compiler flags is as follows:
- [`CMAKE_C_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html)
- [`CMAKE_C_FLAGS_<CONFIG>`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_CONFIG.html)
- flags added by [`add_compile_options()`](https://cmake.org/cmake/help/latest/command/add_compile_options.html)
- flags added by [`target_compile_options()`](https://cmake.org/cmake/help/latest/command/target_compile_options.html)

Additionally, `CMAKE_C_FLAGS` can be initialized using CMake's builtin defaults (for example, `/DWIN32 /D_WINDOWS` for MSVC) or by the [`CFLAGS`](https://cmake.org/cmake/help/latest/envvar/CFLAGS.html) environment variable.

If a user sets the latter, its value is consumed first without a chance to override flags set by the build system.

**Comment by hebasto** [comment]
>    - [ ] Set `-fvisibility-inlines-hidden`? (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1124273356)

GCC:
```
cc1: warning: command-line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
```

So removing this task from the list.

**Comment by hebasto** [comment]
During reviewing of #1113, there was a [suggestion](https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1179172504):
> And expressing `Coverage` as build type in CMake seems to use build types in the right way.

Later, https://github.com/bitcoin-core/secp256k1/pull/1188 introduced a new target `noverify_tests` and made the other target `tests` _dependent_  on whether the build system is configured for coverage analysis or not.

Unfortunately, CMake has no any straightforward way to skip targets in certain configuration.
My draft attempt uses the [`EXCLUDE_FROM_DEFAULT_BUILD_COVERAGE`](https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_DEFAULT_BUILD_CONFIG.html) target property and [generator expressions](https://gitlab.kitware.com/cmake/cmake/-/commit/2cdaf43d966f8407f0fb75ceb131fdca16617915) in the `EXCLUDE_FROM_ALL` target property which, in turn, requires CMake 3.19+. Needless to say, such an implementation increases the complexity of the code.


As @real-or-random rightly [noted](https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1127856040), the current code works only for single-config generators.

Suggesting to re-introduce a trivial `option(SECP256K1_COVERAGE OFF)` which enforces the only available build configuration "Coverage".

**Comment by hebasto** [comment]
In case it would be interested for other developers, here is my preset for cross-building from Linux (I use Ubuntu 22.04) to macOS:
```json
{
  "version": 3,
  "configurePresets": [
    {
      "name": "macos-x86_64",
      "displayName": "Cross-compiling for macOS x86_64",
      "generator": "Unix Makefiles",
      "binaryDir": "${sourceDir}/build",
      "cacheVariables": {
        "CMAKE_SYSTEM_NAME": "Darwin",
        "CMAKE_SYSTEM_PROCESSOR": "x86_64",
        "CMAKE_C_COMPILER": "/usr/bin/clang;--target=x86_64-apple-darwin",
        "CMAKE_C_FLAGS": "-fuse-ld=/usr/bin/ld64.lld-14 -mmacosx-version-min=10.15 -mlinker-version=609 -Wno-unused-command-line-argument",
        "CMAKE_OSX_SYSROOT": "/home/hebasto/SDKs/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers"
      },
      "warnings": {
        "dev": true,
        "uninitialized": true
      }
    }
  ]
}
```

The `llvm` and `lld` packages are required to be installed.

Regarding `Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers` see https://github.com/bitcoin/bitcoin/blob/master/contrib/macdeploy/README.md.

**Comment by hebasto** [comment]
> - [ ] Consider using `COMPILE_FLAGS` or `COMPILE_OPTIONS` to add CFLAGS. `COMPILE_OPTIONS` requires CMake 3.11, while we currently target CMake 3.1 (https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1125545613) 

> ... I figured out that we could set `COMPILE_FLAGS` instead, which supports generator expressions. https://cmake.org/cmake/help/latest/prop_sf/COMPILE_FLAGS.html But if you ask me, that belongs exactly to the category of "making things more CMake-ish", which should not hold up this PR.

Revisiting this issue as we [now](https://github.com/bitcoin-core/secp256k1/pull/1238) have the minimum required CMake 3.13.

Different cases, when we set compiler flags, are as follows:
1. Specific to a _build configuration_. We use dedicated [`CMAKE_C_FLAGS_<CONFIG>`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_CONFIG.html) variables for them.
2. Global flags to request or suppress _warnings_ and errors. We use the [`COMPILE_OPTIONS`](https://cmake.org/cmake/help/latest/prop_dir/COMPILE_OPTIONS.html) top-directory property to handles them which is a well known CMake practice for such cases. Please note that #1240 suggests to use [`add_compile_options()`](https://cmake.org/cmake/help/latest/command/add_compile_options.html) command instead of direct manipulation of the `COMPILE_OPTIONS` property.
3. For _target_-specific flags we use the [`target_compile_options()`](https://cmake.org/cmake/help/latest/command/target_compile_options.html) which is the best CMake practice.

I cannot see what we can do about the original issue, so removing it from the task list. Let me know if I should revert it back.

**Comment by real-or-random** [comment]
> During reviewing of #1113, there was a [suggestion](https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1179172504):
> 
> > And expressing `Coverage` as build type in CMake seems to use build types in the right way.
> 
> Later, #1188 introduced a new target `noverify_tests` and made the other target `tests` _dependent_ on whether the build system is configured for coverage analysis or not.
> 
> Unfortunately, CMake has no any straightforward way to skip targets in certain configuration. My draft attempt uses the [`EXCLUDE_FROM_DEFAULT_BUILD_COVERAGE`](https://cmake.org/cmake/help/latest/prop_tgt/EXCLUDE_FROM_DEFAULT_BUILD_CONFIG.html) target property and [generator expressions](https://gitlab.kitware.com/cmake/cmake/-/commit/2cdaf43d966f8407f0fb75ceb131fdca16617915) in the `EXCLUDE_FROM_ALL` target property which, in turn, requires CMake 3.19+. Needless to say, such an implementation increases the complexity of the code.
> 
> As @real-or-random rightly [noted](https://github.com/bitcoin-core/secp256k1/pull/1113#discussion_r1127856040), the current code works only for single-config generators.
> 
> Suggesting to re-introduce a trivial `option(SECP256K1_COVERAGE OFF)` which enforces the only available build configuration "Coverage".

What about using a CMake preset for Coverage builds, which just sets the right values? I think this could be a bit nicer than an option `SECP256K1_COVERAGE` but we'd need to try.

**Comment by hebasto** [comment]
>    * [ ]  Consider setting CMake's default of /MD for MSVC also in autotools builds.

https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1458005771:
> Nevertheless, as for reasonable defaults, [my impression is that /MD has fewer issues and is what most users would expect, in particular from a library](https://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt?noredirect=1&lq=1) (see also [jedisct1/libsodium#1215](https://github.com/jedisct1/libsodium/discussions/1215) ), and I guess there's a reason why the CMake default is `MultiThreadedDLL` (where the DLL part corresponds to /MD)

@sipsorcery What do you think about that?

**Comment by sipsorcery** [comment]
Without looking into which dll or exe it was applying to /MD would be a BIG change for the Windows build. The fact that the final bitcoind is a statically linked exe cascades down to most, if not all, of the dependencies.

In my experience /MD (dynamically linked) is the default but then so are dynamically linked exe's. I suspect someone decided to make bitcoind statically linked to avoid dll hell and/or a dependency introducing a vulnerability. Either way it is currently statically linked and again it would be a BIG change to make it not so.

If bitcoind on Windows is going to stay statically linked then I think it would end up being a lot of fighting to change any of the artifacts to /MD.

/MT and /MTd get my vote.

**Comment by real-or-random** [comment]
@sipsorcery Thanks for commenting. 

Perhaps there's a slight misunderstanding here. I think there are two separate issues: 
 1. How should the bitcoind build libsecp256k1?
 2. What is the default for libsecp256k1?

The latter is our question. libsecp256k1 has many other in the ecosystem users beside bitcoind. (In fact, that's the reason why it is a separate library.) And we would like to set a reasonable default for them. 

> In my experience /MD (dynamically linked) is the default but then so are dynamically linked exe's. 

This makes me think that we should make /MD the default. Just because that's most common on Windows.

> I suspect someone decided to make bitcoind statically linked to avoid dll hell and/or a dependency introducing a vulnerability. Either way it is currently statically linked and again it would be a BIG change to make it not so.
>If bitcoind on Windows is going to stay statically linked then I think it would end up being a lot of fighting to change any of the artifacts to /MD.

Yes, I see that this will be a mess. But when building libsecp256k1 for bitcoind, we can override anything we want and simply set /MT or /MTd.

**Comment by hebasto** [comment]
>    * [ ]  Consider setting CMake's default of /MD for MSVC also in autotools builds. Perhaps make `CMAKE_MSVC_RUNTIME_LIBRARY` a CMake cache variable. ([build: Add CMake-based build system #1113 (comment)](https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1458005771))

On the current master branch, the user is able to specify the MSVC runtime library by providing the [`CMAKE_MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) variable at the configuration stage. I'm not sure how the caching of it might improve the user experience.

Going to skip this goal for now.

cc @real-or-random

**Comment by hebasto** [comment]
>    * [ ]  Consider setting CMake's default of /MD for MSVC also in autotools builds... ([build: Add CMake-based build system #1113 (comment)](https://github.com/bitcoin-core/secp256k1/pull/1113#issuecomment-1458005771))

I think it's OK to leave the defaults as they are for the following reason: After introducing the CMake-based build system, using MSVC with Autotools can be reasonably considered for testing purposes only. Additionally, it is beneficial to test Windows binaries with different MSVC runtime library options.

Anyway, both routines, in CMake and in Autotools, allow the user to specify the MSVC runtime library explicitly.

Removing this task from the list. Please let me know if you would like me to revert it back.

**Comment by hebasto** [comment]
>    * [ ]  Consider [CMAKE_COMPILE_WARNING_AS_ERROR](https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILE_WARNING_AS_ERROR.html) for CMake 3.24+ ([build: Improve `SECP_TRY_APPEND_DEFAULT_CFLAGS` macro #1241 (comment)](https://github.com/bitcoin-core/secp256k1/pull/1241#issuecomment-1509008580))

CMake continuously introduces new abstractions for different aspects of the building process. Another example is `DLL_NAME_WITH_SOVERSION`: https://github.com/bitcoin-core/secp256k1/pull/1270#discussion_r1243384113.

I don't think it would be beneficial to have two code paths depending on the actual CMake version. It would introduce additional complexity to the code and potentially lead to deviations in the user experience.

We might review such new CMake's features in the future when we are about to bump the minimum required CMale version.

It seems unreasonable to have a tracking issue for such features.

Removing this task from the list. Please let me know if you would like me to revert it back.

**Comment by real-or-random** [comment]
> I think it's OK to leave the defaults as they are for the following reason: After introducing the CMake-based build system, using MSVC with Autotools can be reasonably considered for testing purposes only.

That's a good point, I buy that argument.

**Comment by real-or-random** [comment]
> I don't think it would be beneficial to have two code paths depending on the actual CMake version. It would introduce additional complexity to the code and potentially lead to deviations in the user experience.

I agree in general. Though there may be exceptions on a case-by-case basis. We have a few places where we check the value of `CMAKE_VERSION`, and I think they all make sense.

> We might review such new CMake's features in the future when we are about to bump the minimum required CMale version.

You mean when we bump, we should just read CMake's changelog? That makes sense to me.

Another possibility is that we add a comment to the affected code, e.g., `TODO: Consider DLL_NAME_WITH_SOVERSION when bumping to CMake x.y`. I would ACK such a comment, but yeah, just reading the changelog seems good enough, too.

**Comment by hebasto** [comment]
> > I don't think it would be beneficial to have two code paths depending on the actual CMake version. It would introduce additional complexity to the code and potentially lead to deviations in the user experience.
> 
> I agree in general. Though there may be exceptions on a case-by-case basis. We have a few places where we check the value of `CMAKE_VERSION`, and I think they all make sense.

Agree. That was my idea that I failed to express clearly and fully :)

> > We might review such new CMake's features in the future when we are about to bump the minimum required CMale version.
> 
> You mean when we bump, we should just read CMake's changelog?

Yes.

> Another possibility is that we add a comment to the affected code, e.g., `TODO: Consider DLL_NAME_WITH_SOVERSION when bumping to CMake x.y`.

Once we start adding such comments, we have to do some work at every CMake release.

> I would ACK such a comment, but yeah, just reading the changelog seems good enough, too.

I'd prefer the latter :)

**Comment by real-or-random** [comment]
> > * [ ]   Compute string `secp256k1` (e.g., in `target_link_libraries`) as substring of `PROJECT_NAME`. That will help with distinguishing forks. ([cmake: Rename project to "libsecp256k1" #1229 (comment)](https://github.com/bitcoin-core/secp256k1/pull/1229#discussion_r1130064718)).
> 
> The recommended practice is to treat a project name and target names as independent concepts.

Okay, then let's just drop this item.

Then we're only left with one item: unified docs. We can consider that one tracked in https://github.com/bitcoin-core/secp256k1/pull/1372.
