### ISSUE TITLE
ci: Future of CI after Cirrus pricing change 

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1392]
Roadmap (keeping this up to date):

I think the natural way forward for us is:
 - [x] Move native Windows tasks to GitHub Actions (#1389 and #1397)
 - [x] Move SageMath task to GitHub Actions (#1399)
 - [x] Move native macOS tasks to GitHub Actions, this will convert them to x86_64 unfortunately (#1394, #1404)
 - Move Linux tasks to the Bitcoin Core persistent workers or alternatively to GitHub Actions
   - [x] wine/msvc tasks (converting them to native windows in #1401)
   - [x] wine/mingw tasks (#1398)
   - [x] actual normal Linux tasks (#1396)
   - [x] special tasks like qemu/sanitizers (#1406, #1409)

Possible follow-ups:
 - ~Consider using [artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) to move the Docker image from the Docker build job to the actual CI job (for Linux tasks).~ (Not worth the hassle, the current approach seems to work well.)<details><summary>Details</summary>
 This should be a [cleaner solution](https://github.com/bitcoin-core/secp256k1/pull/1398#issuecomment-1677074743), but it adds some complexity. It's also worth checking if this avoids [network issues](https://github.com/bitcoin-core/secp256k1/pull/1396#issuecomment-1684108729). In terms of delay, [this adds about 12 min uploading time to the Docker build job, but avoids about 1 min delay in the actual CI jobs](https://github.com/bitcoin-core/secp256k1/pull/1396#issuecomment-1686387785) as compared to the current solution that relies purely on the GHA cache (#1398).  So this will speed up CI if we could avoid re-uploading existing artifacts, e.g., have another digest file that just stores the SHA256, and re-upload only if the SHA does not match. But all of this is probably not worth the complexity if the current approach with the cache turns out to be good enough.</details>
 - [x] Enable Valgrind on macOS again now that the macOS tasks run on x86_64 (#1151, #1412)
 - Bring back some ARM testing (see for details: https://github.com/bitcoin-core/secp256k1/pull/1394#issuecomment-1682321329)
   - [x] Add a task for ctimetest on ARM64/Linux/Valgrind on Cirrus CI using free minutes or the self-hosted runner  (#1426)
   - [x] Add more ARM64 tests on QEMU (#1414)
   - [ ] Add ARM32 tests (https://github.com/bitcoin-core/secp256k1/pull/1426#issuecomment-1728543515) 
 - [x] Consider moving the `git` safe directory stuff to `run-in-docker-action` (https://github.com/bitcoin-core/secp256k1/pull/1411)
 - [ ] After the migration, check if the build matrix still makes sense 
 - [ ] cosmetics: Job names could need a rework
 - [ ] cosmetics: Printing of log files could be improved

Other related PRs:
 - [x] https://github.com/bitcoin-core/secp256k1/pull/1403
 - [x] https://github.com/bitcoin-core/secp256k1/pull/1410

----

Corresponding Bitcoin Core issue: https://github.com/bitcoin/bitcoin/issues/28098

Cirrus CI will cap the community cluster, see [cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci](https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/). As with Core, the pricing model makes it totally unreasonable to pay for compute credits (multiple thousand USD / month).

The plan in Bitcoin Core is to move native Windows+macOS tasks to GitHub Actions, and move Linux tasks to persistent workers (=self-hosted). If I read the Bitcoin Core IRC [meeting notes](https://bitcoin.jonasschnelli.ch/ircmeetings/logs/bitcoin-core-dev/2023/bitcoin-core-dev.2023-08-03-14.00.log.html#l-79) correctly, @MarcoFalke [said](https://bitcoin.jonasschnelli.ch/ircmeetings/logs/bitcoin-core-dev/2023/bitcoin-core-dev.2023-08-03-14.00.log.html#l-99) these workers will also be available for libsecp256k1.

But the devil is in the details: 

For macOS, we need to take also #1153 into account. It seems that [GitHub-hosted macOS runners are on x86_64](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). The good news is that Valgrind should work again then, but the (very) bad is that this will reduce our number of native ARM tasks to zero. We still have some QEMU tasks, but we can't even the run the Valgrind cttimetests on them (maybe this would now work with MSan?!) @MarcoFalke Are the self-hosted runners only x86_64? 

For Linux tasks, the meeting notes say that the main reason for using persistent workers is that some tasks require a very specific environment (e.g., the [USDT ASan job](https://github.com/bitcoin/bitcoin/pull/28161)). I don't think we have such requirements, so I tend to think that moving everything to GitHub Actions is a bit cleaner for us. With a persistent worker, Cirrus CI anyway acts only as a "coordination layer" between the worker and GitHub. Yet another way is to the self-hosted runners with GitHub Actions, see my comment https://github.com/bitcoin/bitcoin/issues/28098#issuecomment-1665661274).

**Comment by real-or-random** [comment]
Ok, then it probably makes sense to do what I suggested in #1153, namely move ARM tasks to Linux, and reduce the number of our macOS tasks.

**Comment by real-or-random** [comment]
> > moving everything to GitHub Actions is a bit cleaner for us
> 
> Sounds interesting. I wonder how (and if) docker images can be cached, along with ccache, etc...

Yeah, we'll need to see.

And I agree that "in the short run it seems easier to stick to Cirrus for now, because the diff is a lot smaller (just replace container: in the yml with persistent_worker:, etc)" (https://github.com/bitcoin/bitcoin/issues/28098#issuecomment-1665708491). We should probably do this first, and then see if we're interested in moving to GitHub Actions fully.

**Comment by hebasto** [comment]
> For macOS, we need to take also #1153 into account. It seems that [GitHub-hosted macOS runners are on x86_64](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). The good news is that Valgrind should work again then...

For such a case, it is good to see some progress in https://github.com/bitcoin-core/secp256k1/pull/1274 :)

**Comment by hebasto** [comment]
> > moving everything to GitHub Actions is a bit cleaner for us
> 
> Sounds interesting. I wonder how (and if) docker images can be cached, along with ccache, etc...

See https://github.com/bitcoin-core/secp256k1/pull/1396.

**Comment by hebasto** [comment]
>    * [ ]  Move native Windows tasks to GitHub Actions (solved by [ci: Run "Windows (VS 2022)" job on GitHub Actions #1389](https://github.com/bitcoin-core/secp256k1/pull/1389))
> 
>    * [ ]  Move Linux tasks to the Bitcoin Core persistent workers
> 
>    * [ ]  (Optional, in the long run:) Move Linux tasks to GitHub actions

There are open PRs for all of the mentioned items. It would be more productive, if we somehow prioritise them to spend our time until Sept. 1st more effectively.

**Comment by real-or-random** [comment]
Yes, we should in principle proceed in the order of the list above.  But it doesn't need to be very strict. For example, if it turns out that #1396 is ready by Sep 1st, we can skip "Move Linux tasks to the Bitcoin Core persistent workers".

**Comment by hebasto** [comment]
>    * [ ]  Move Linux tasks to the Bitcoin Core persistent workers

It seems reasonable to split this task in two ones, depending on the underlying architecture: `x86_64` and `arm64`, because the GitHub hosted runners lack [support](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) for `arm64`.

**Comment by real-or-random** [comment]
@hebasto Hm, we currently don't have native Linux arm64 jobs, so we can't "move" them over. We could add some (see #1163 and https://github.com/bitcoin-core/secp256k1/pull/1394#issuecomment-1671784065).

I tend to think that is also acceptable to wait for https://github.com/github/roadmap/issues/528, it's currently planned for the end of the year. Then we could move macOS back to ARM. Until that happens, perhaps we can add a QEMU jobs that run the ctimetests on MSan (clang-only) at least. Note to self: We need `apt-get install libclang-rt-dev:arm64` and this works with
```
HOST="aarch64-linux-gnu" CC="clang --target=aarch64-linux-gnu" WRAPPER_CMD="qemu-aarch64"
```

I updated the list above with optional items.

**Comment by hebasto** [comment]
>    * [ ]  Enable Valgrind on macOS again now that the macOS tasks run on x86_64 ([Constant-time tests on macOS #1151](https://github.com/bitcoin-core/secp256k1/issues/1151))

While it worked on macOS Catalina back in time, it seems a couple of suppression for `/usr/lib/libSystem.B.dylib` and `/usr/lib/dyld` are needed.

**Comment by real-or-random** [comment]
Oh thanks for checking. Have you tried the supplied suppression file (https://github.com/LouisBrunner/valgrind-macos/blob/main/darwin19.supp)? If it doesn't solve the problem, we could try to upstream the additional suppressions, see also https://github.com/LouisBrunner/valgrind-macos/issues/15.

**Comment by hebasto** [comment]
> Have you tried the supplied suppression file ([LouisBrunner/valgrind-macos@`main`/darwin19.supp](https://github.com/LouisBrunner/valgrind-macos/blob/main/darwin19.supp?rgh-link-date=2023-08-25T08%3A29%3A18Z))?

Yes, I have. It is does not change the outcome.

**Comment by real-or-random** [comment]
Do you think maintaining the suppressions is a problem? I don't think it's a big deal.

> UPD. I used [LouisBrunner/valgrind-macos@main/darwin22.supp](https://github.com/LouisBrunner/valgrind-macos/blob/main/darwin22.supp?rgh-link-date=2023-08-25T08%3A46%3A28Z) as we run Ventura.

Okay, sure, I got confused and looked at the wrong file.

**Comment by hebasto** [comment]
> Do you think maintaining the suppressions is a problem? I don't think it's a big deal.

You mean, in this repository?

**Comment by real-or-random** [comment]
> > Do you think maintaining the suppressions is a problem? I don't think it's a big deal.
> 
> You mean, in this repository?

Yes... I don't think it will be a lot of work, but I guess we should still submit it upstream first. If they merge it quickly, then it's easiest for us. I can take care if you don't have the bandwidth.

**Comment by hebasto** [comment]
> > * [ ]   Enable Valgrind on macOS again now that the macOS tasks run on x86_64 ([Constant-time tests on macOS #1151](https://github.com/bitcoin-core/secp256k1/issues/1151))
> 
> While it worked on macOS Catalina back in time, it seems a couple of suppression for `/usr/lib/libSystem.B.dylib` and `/usr/lib/dyld` are needed.

FWIW, it works with no additional suppressions on [`macos-12`](https://github.com/actions/runner-images#available-images).

**Comment by hebasto** [comment]
> I can take care if you don't have the bandwidth.

It would be nice because I have no x86_64 macOS Ventura available.

**Comment by real-or-random** [comment]
> FWIW, it works with no additional suppressions on [macos-12](https://github.com/actions/runner-images#available-images).

Oh ok, should we then just use this for now?

> > I can take care if you don't have the bandwidth.
> 
> It would be nice because I have no x86_64 macOS Ventura available.

I don't have any macOS available. ;)

**Comment by hebasto** [comment]
> > FWIW, it works with no additional suppressions on [macos-12](https://github.com/actions/runner-images#available-images).
> 
> Oh ok, should we then just use this for now?

Done in https://github.com/bitcoin-core/secp256k1/pull/1412.

**Comment by hebasto** [comment]
> > > Do you think maintaining the suppressions is a problem? I don't think it's a big deal.
> > 
> > 
> > You mean, in this repository?
> 
> Yes... I don't think it will be a lot of work, but I guess we should still submit it upstream first.

See https://github.com/LouisBrunner/valgrind-macos/pull/96 as a first step.

**Comment by real-or-random** [comment]
> * [ ]  Add a task for ctimetest on ARM64/Linux/Valgrind on Cirrus CI using free minutes or the self-hosted runner

Hm, it appears that Cirrus' "Dockerfile as a CI environment" feature won't work with persistent workers (see #1418). Now that I think about it, that's somewhat expected (e.g., where should the built images be pushed?). 

Alternatives:
 - Set up our own Docker pipeline on Cirrus (but that seems overkill) 
 - Use the free minutes (but they're [shared among all repos of bitcoin-core](https://github.com/bitcoin-core/secp256k1/pull/1414#issuecomment-1703864886))
 - Go back to the QEMU approach and try to [compile compiler-rt on our own](https://github.com/bitcoin-core/secp256k1/pull/1414#issuecomment-1701339719) (but that's a rabbit hole)
 - Don't use a Dockerfile (but that means we won't get gcc-snapshot, unless we build it every time or cache it somehow)
 - Do nothing (and wait for [native ARM64 on GHA](https://github.com/github/roadmap/issues/528))

I think we should do one of the last two?

**Comment by real-or-random** [comment]
> A persistent worker will persist the docker image itself, after the first run on the hardware. 

Thanks for chiming in. Wouldn't we also need to make sure that images get pruned from time to time? Or does podman handle this automatically?

> `podman image --file $docker_file --name --env $bla --name $bla_image_name && podman container kill $ci_bla_name && podman run -it --rm --name $ci_bla_name $bla_image_name ./ci.sh`

I assume the first step performs the caching automatically, rebuildung layers only as necessary? Sorry, I'm not familiar with podman, I have only used Docker so far.

> Alternatively it may be possible to find a sponsor to cover the cost (if it is not too high) on cirrus directly, while native arm64 isn't on GHA.

Right, yeah, I'm just not sure if I want to spend time on this. 

> I can look at the llvm issue next week, if time permits.

Ok sure, but I recommend not spending too much time on it. It also won't help with GCC (I added a note aboce).

**Comment by real-or-random** [comment]
Okay, then I think this approach is probably simpler than I expected. I'm not sure if I have the time this week, but I'll look into that soon. (Or @hebasto, if you want to give it a try, feel free to go ahead, of course. My plan was to simply "abuse" the existing Dockerfile to avoid maintaining a second one, at the cost of a somewhat larger image. The existing file should build fine except that debian won't let you install an arm64 cross-compiler on arm64. So we'd need to add some check to skip these packages when we're on arm64, see https://github.com/bitcoin-core/secp256k1/pull/1163/files#diff-751ef1d9fd31c5787e12221f590262dcf7d96cfb166d456e06bd0ccab115b60d .)

> If you mean reaching out to a sponsor, I am happy to reach out, if there is a cost estimate.

Okay, thanks, but let's first try docker/podman then.

**Comment by real-or-random** [comment]
The migration is done, but there are still a few unticked checkboxes. (And I've just added two.) None of them are crucial, but I plan to work on them soon, so I'd like to keep this open for now. We could also close this issue here and add a new tracking issue, or open separate issues for the remaining items, if people think that makes tracking easier.

**Comment by hebasto** [comment]
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by real-or-random** [comment]
> Are large runners available for public repos?

Ha, okay, you're right. No, "larger runners" are always billed per minute, i.e., they're not free for public repos. And it seems that they're not planning to provide M1 "standard runners". At least https://github.com/github/roadmap/issues/528#issuecomment-1743546984 has been closed now. That means we should stick to the Cirrus runners for ARM.

**Comment by real-or-random** [comment]
> And it seems that they're not planning to provide M1 "standard runners"

That has changed now: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by hebasto** [comment]
The remaining unchecked boxes from the OP are:

>    * [ ]  After the migration, check if the build matrix still makes sense
>    * [ ]  cosmetics: Job names could need a rework
>    * [ ]  cosmetics: Printing of log files could be improved

Would it make sense to open dedicated issues for better visibility and close this one?

**Comment by real-or-random** [comment]
Let's just close this entirely. 

Happy to see PRs addressing these remaining items, but they're not crucial, and they're pretty obvious from the CI output itself, so there's no need to track them.
