### ISSUE TITLE
Tracking issue for non-autotool builds

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#929]
We started with 

```
gcc -Wall -Wextra -Wno-unused-function -O2 -I. -c ./src/secp256k1.c -DSECP256K1_BUILD -D ECMULT_GEN_PREC_BITS=4 -D ECMULT_WINDOW_SIZE=15
```

The goal is to get rid of most of the command line arguments, at least on GCC and clang:

 - [x] `-DSECP256K1_BUILD`: #928
 - [ ] `-I` #925 
 - [ ] `-D ECMULT_GEN_PREC_BITS=4 -D ECMULT_WINDOW_SIZE=15`: See discussion in #918. We could even print the config using `#pragma message`)
 - [ ] `-Wno-unused-function`: We could add a `#pragma` or better add `__attribute__ ((unsused))` to the relevant functions.
 - [ ] `-Wall -Wextra`: We could set this via `#pragmas` but maybe we should leave this to the user.
 - [ ] `-O2`: I think we should really leave this to the user.
 - [ ] Add section to README
 - [ ] Add CI jobs to test these builds

**Comment by gmaxwell** [comment]
>  -Wno-unused-function: We could add a #pragma or better add __attribute__ ((unsused)) to the relevant functions.

There are no unused functions except for ones that are unneeded because of test harness or module configuration options.  I think they should be ifdefed out when their relevant modules are disabled.  This is ever so slightly less clean because it breaks module isolation but it has a big win that when the code changes to make them actually unused we'll get warnings, and I think that is well worth it.

>  -Wall -Wextra: We could set this via #pragmas but maybe we should leave this to the user.

Yeah leave that to the user. :P  Also -pedantic -std=c89 ... but the CI should be testing that way and probably with -Werror at least in one config since the CI's compiler is stable (never subject the general public to Werror, since god knows what their compiler will warn on--- but it's reasonable to expect development to be always warning clean on a single stable target compiler.)

One missing thing here is the loss of assembly optimizations.  Because arm requires an external assembler and 64-bit windows doesn't support inline asm at all, this is kinda unfortunate.   The performance loss on 32-bit arm from losing access to assembly is phenomenal. It's kinda dumb that joe-hardware-wallet-dev is going to almost double his signing time (schnorrsig_sign 872us vs 472us on a 1.2GHz arm7) just due to using a naive build process, and keep in mind HWW are much lower clockrate devices.

**Comment by real-or-random** [comment]
> > -Wno-unused-function: We could add a #pragma or better add **attribute** ((unsused)) to the relevant functions.
> 
> There are no unused functions except for ones that are unneeded because of test harness or module configuration options. 

Sure? I think at least the multimultiplication functions and the scratch space functions are currently unused.

**Comment by gmaxwell** [comment]
Ah, well-- they're used by the tests.  They could become tests-only until they're in use. I still think that is better than compiling with unused functions warnings off.

**Comment by gmaxwell** [comment]
I think for the ASM issue,  we could provide an example command line to also include the ASM and set a -DUSE_ASM,   and we could  check if `__ARM_ARCH_7__` (and the other relevant macros) are set without the USE_ASM define and print a warning that it will be 2x slower than otherwise.

E.g. this currently works:

```
gcc -Wall -Wextra -Wno-unused-function  -O2 -I. -Iinclude/ -DUSE_EXTERNAL_ASM -D ECMULT_GEN_PREC_BITS=4 -D ECMULT_WINDOW_SIZE=15 -o tests ./src/tests.c src/asm/field_10x26_arm.s
```

And it isn't too bad.

**Comment by real-or-random** [comment]
Now that #1042 has been merged, we need to build multiple modules:
```
gcc -c src/secp256k1.c src/precomputed_*.c -DECMULT_GEN_PREC_BITS=4 -DECMULT_WINDOW_SIZE=15
ar rcs secp256k1.a secp256k1.o precomputed_*.o
```

**Comment by hebasto** [comment]
>    * [ ]  `-Wall -Wextra`: We could set this via `#pragmas` but maybe we should leave this to the user.
> 
>    * [ ]  `-O2`: I think we should really leave this to the user.

Agreed, both options should be left to the user.

When building a shared library, providing the `-Wl,--no-undefined` option might be a good way to ensure that the resulted library is OK:
```
gcc -O2 -fPIC -c src/secp256k1.c src/precomputed_*.c
gcc secp256k1.o precomputed_*.o -shared -Wl,--no-undefined -o libsecp256k1.so
```
